genres: [
  'Electronic',
  'Rock',
  'Hip Hop',
  'Jazz']
styles: [
    'House',
    'Experimental',
    'Synth-pop',
    'Techno',
    'Ambient',
    'Electro',
    'Trance',
    'Downtempo',
    'Disco',
    'Tech House',
    'Noise',
    'Deep House',
    'Drum n Bass',
    'Progressive House',
    'Industrial',
    'Euro House',
    'Abstract',
    'Hardcore',
    'Minimal',
    'Pop Rock',
    'Breakbeat',
    'Drone',
    'Progressive Trance',
    'IDM',
    'New Wave',
    'Breaks',
    'Dark Ambient',
    'Dance-pop',
    'Hard Trance',
    'Electro House',
    'Acid',
    'Alternative Rock',
    'Europop',
    'Leftfield',
    'Dubstep',
    'Psy-Trance',
    'Dub',
    'Indie Rock',
    'Hard House',
    'Hip Hop',
    'New Age',
    'Funk',
    'Modern Classical',
    'Ballad',
    'EBM',
    'Italo-Disco',
    'Trip Hop',
    'Jungle',
    'Soundtrack',
    'Hardstyle',
    'Soul',
    'Synthwave',
    'Garage House',
    'Darkwave',
    'Vaporwave',
    'Happy Hardcore',
    'Eurodance',
    'UK Garage',
    'Tribal',
    'Italodance',
    'Vocal',
    'Future Jazz',
    'RnB/Swing',
    'Glitch',
    'Harsh Noise Wall',
    'Indie Pop',
    'Pop Rap',
    'Latin',
    'Dub Techno',
    'Gabber',
    'Avantgarde',
    'Breakcore',
    'Hi NRG',
    'Power Electronics',
    'Acid House',
    'Dungeon Synth',
    'Psychedelic Rock',
    'Punk',
    'Minimal Techno',
    'Musique Concrète',
    'Field Recording',
    'Chiptune',
    'Freestyle',
    'Nu-Disco',
    'Post-Punk',
    'Contemporary R&B',
    'Tribal House',
    'Big Beat',
    'Berlin-School',
    'Acid Jazz']