query: null
genre: 'Electronic' # Rock, Electronic, Hip Hop, Jazz
style: 'Minimal' 
country: null
year: null
MODEL_SR: 16000
# type: 'House'
# title: None
# release_title: None 
# credit: None
# artist: None
# label: None
# format: None 
# track: None 
# submitter: None 
# contributor: None